apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck
  namespace: mynamespace
  labels:
    app: rundeck
spec:
  storageClassName: gp2-expandable-encrypted
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi