
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rundeck-RoleBinding
  namespace: mynamespace
  labels:
   app: rundeck
subjects:
- kind: ServiceAccount
  name: rundeck
  namespace: mynamespace
roleRef:
  kind: ClusterRole
  name: rundeck-role
  apiGroup: rbac.authorization.k8s.io